import type { Resource, Chunk } from './types';

export const mockResources: Resource[] = [
  {
    id: 'res_1',
    title: 'Q3 Financial Report 2025',
    type: 'pdf',
    folder_name: 'Finance',
    playlist_name: 'Quarterly Reviews',
    processing_status: 'completed',
    rag_status: 'ready',
    is_embedded: true,
    chunk_count: 145,
    vector_count: 145,
    search_index_count: 145,
    transcript_chars: 45000,
    summary_chars: 1200,
    has_transcript: true,
    has_summary: true,
    created_at: '2026-07-01T10:00:00Z',
    diagnostics: {
      healthy: true,
      health_score: 100,
      health_history: [
        { time: '10:00', score: 10 },
        { time: '10:05', score: 40 },
        { time: '10:10', score: 70 },
        { time: '10:15', score: 90 },
        { time: '10:20', score: 100 },
      ],
      issues: [],
      warnings: [],
      ready_for_retrieval: true,
      can_resume: false,
      can_embed: false,
      supports_summary: false,
    }
  },
  {
    id: 'res_2',
    title: 'All-Hands Meeting June',
    type: 'video',
    folder_name: 'Company Meetings',
    playlist_name: 'All-Hands',
    processing_status: 'failed',
    rag_status: 'failed_embedding',
    is_embedded: false,
    chunk_count: 320,
    vector_count: 150,
    search_index_count: 320,
    transcript_chars: 120500,
    summary_chars: 5000,
    has_transcript: true,
    has_summary: true,
    created_at: '2026-06-28T14:30:00Z',
    diagnostics: {
      healthy: false,
      health_score: 45,
      health_history: [
        { time: '14:30', score: 10 },
        { time: '14:35', score: 30 },
        { time: '14:40', score: 50 },
        { time: '14:45', score: 80 },
        { time: '14:50', score: 45 },
      ],
      issues: ['Embedding process timed out at chunk 151.'],
      warnings: ['Chunk count does not match vector count.'],
      failed_stage: 'embedding',
      last_completed_stage: 'subchaptering',
      ready_for_retrieval: false,
      can_resume: true,
      can_embed: true,
      supports_summary: true,
    }
  },
  {
    id: 'res_3',
    title: 'Product Architecture v4',
    type: 'docx',
    folder_name: 'Engineering',
    playlist_name: 'Architecture Docs',
    processing_status: 'processing',
    rag_status: 'chunked',
    is_embedded: false,
    chunk_count: 85,
    vector_count: 0,
    search_index_count: 0,
    transcript_chars: 22000,
    summary_chars: 0,
    has_transcript: true,
    has_summary: false,
    created_at: '2026-07-02T09:15:00Z',
    diagnostics: {
      healthy: true,
      health_score: 80,
      health_history: [
        { time: '09:15', score: 10 },
        { time: '09:20', score: 30 },
        { time: '09:25', score: 50 },
        { time: '09:30', score: 70 },
        { time: '09:35', score: 80 },
      ],
      issues: [],
      warnings: ['Not yet vector-ready. Lexical search unavailable.'],
      last_completed_stage: 'chunking',
      ready_for_retrieval: false,
      can_resume: false,
      can_embed: false,
      supports_summary: false,
    }
  },
  {
    id: 'res_4',
    title: 'Customer Interview - Acme Corp',
    type: 'audio',
    folder_name: 'User Research',
    playlist_name: 'Acme Study',
    processing_status: 'failed',
    rag_status: 'failed_transcribing',
    is_embedded: false,
    chunk_count: 0,
    vector_count: 0,
    search_index_count: 0,
    transcript_chars: 0,
    summary_chars: 0,
    has_transcript: false,
    has_summary: false,
    created_at: '2026-07-03T08:00:00Z',
    diagnostics: {
      healthy: false,
      health_score: 10,
      health_history: [
        { time: '08:00', score: 10 },
        { time: '08:05', score: 10 },
        { time: '08:10', score: 10 },
      ],
      issues: ['Audio file format not supported or corrupted.'],
      warnings: [],
      failed_stage: 'transcribing',
      last_completed_stage: 'uploaded',
      ready_for_retrieval: false,
      can_resume: false,
      can_embed: false,
      supports_summary: true,
    }
  },
  {
    id: 'res_5',
    title: 'System Architecture Diagram',
    type: 'image',
    folder_name: 'Engineering',
    playlist_name: 'Architecture Docs',
    processing_status: 'completed',
    rag_status: 'ready',
    is_embedded: true,
    chunk_count: 5,
    vector_count: 5,
    search_index_count: 5,
    transcript_chars: 1200,
    summary_chars: 200,
    has_transcript: true,
    has_summary: true,
    created_at: '2026-07-01T11:20:00Z',
    diagnostics: {
      healthy: true,
      health_score: 100,
      health_history: [
        { time: '11:20', score: 20 },
        { time: '11:25', score: 60 },
        { time: '11:30', score: 100 },
      ],
      issues: [],
      warnings: [],
      ready_for_retrieval: true,
      can_resume: false,
      can_embed: false,
      supports_summary: false,
    }
  }
];

export const mockChunks: Record<string, Chunk[]> = {
  'res_2': Array.from({ length: 15 }, (_, i) => ({
    id: `chunk_${i}`,
    resource_id: 'res_2',
    chunk_index: i,
    content: i < 5 ? `We need to align on the Q4 roadmap. Specifically, the integration with the new API... (Transcript segment ${i})` : `This chunk failed to embed properly. (Transcript segment ${i})`,
    has_vector: i < 5,
    timestamp: `00:${i.toString().padStart(2, '0')}:00`,
    chapter: i < 10 ? 'Roadmap Discussion' : 'Q&A'
  })),
  'res_1': Array.from({ length: 5 }, (_, i) => ({
    id: `chunk_${i}`,
    resource_id: 'res_1',
    chunk_index: i,
    content: `Financial metrics for quarter ${i} show a steady increase in MRR, largely driven by enterprise expansions.`,
    has_vector: true,
    page_number: i + 1,
    chapter: 'Financial Metrics'
  }))
};
